export enum ErrorCode {
  // Auth
  AUTH_UNAUTHORIZED = "AUTH_UNAUTHORIZED",
  AUTH_FORBIDDEN = "AUTH_FORBIDDEN",

  // Users
  USER_ALREADY_EXISTS = "USER_ALREADY_EXISTS",
  USER_NOT_FOUND = "USER_NOT_FOUND",

  // Validation
  VALIDATION_ERROR = "VALIDATION_ERROR",

  // Business Rules
  BUSINESS_ERROR = "BUSINESS_ERROR",
  NOT_FOUND = 'NOT_FOUND',

  // Prisma / Database
  DB_CONFLICT = "DB_CONFLICT",
  DB_NOT_FOUND = "DB_NOT_FOUND",
  DB_FOREIGN_KEY = "DB_FOREIGN_KEY",
  DB_ERROR = "DB_ERROR",

  // Internal Generic
  INTERNAL_ERROR = "INTERNAL_ERROR",
}