export enum ErrorCode {
  INVALID_PROMPT = 'INVALID_PROMPT',
  OPENAI_ERROR = 'OPENAI_ERROR',
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  RATE_LIMIT = 'RATE_LIMIT',
  INTERNAL_ERROR = 'INTERNAL_ERROR',
  EXTERNAL_API_ERROR = "EXTERNAL_API_ERROR",
}
